name: 'Prepare Platformio'
description: 'Load cache'

inputs:
  python-version:
    description: 'Installed Python version'
    required: true

runs:
  using: "composite"
  steps:
    - name: load PlatformIO cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.platformio
        key: ${{ runner.os }}-py-${{ inputs.python-version }}-pio-cache-${{ hashFiles('**/platformio.ini') }}
