name: "DOC build and deploy"

on:
  workflow_dispatch:
  #push:
  #  paths:
  #    - "**/*.h"
  #    - "**/*.c"
  #    - "**/*.cpp"
  #    - "utils/**/*"
  #    - "!.github/workflows/**/*"
  #    - ".github/workflows/documentation.yaml"
  #pull_request:
  #  paths:
  #    - "**/*.h"
  #    - "**/*.c"
  #    - "**/*.cpp"
  #    - "utils/**/*"
  #    - "!.github/workflows/**/*"
  #    - ".github/workflows/documentation.yaml"

jobs:
  docs-build-deploy:
    name: Generate docs on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prerequisites
        uses: ./.github/actions/checkout-python-poetry-platformio

      - name: Install OS dependencies
        run: |
          sudo apt install python3-clang
          sudo apt install doxygen

      - name: Sphinx build
        run: |
          cd utils
          source .venv/bin/activate
          cd docs
          make clean
          make docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: utils/docs/_build/html
          force_orphan: true
