name: "DOC build and deploy"

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.c"
      - "**/*.cpp"
      - "**/*.h"
      - "docs/**/*"
      - "!.github/workflows/**"
      - ".github/workflows/documentation.yaml"
  pull_request:
    paths:
      - "**/*.c"
      - "**/*.cpp"
      - "**/*.h"
      - "docs/**/*"
      - "!.github/workflows/**"
      - ".github/workflows/documentation.yaml"

permissions:
  contents: write

jobs:
  docs-build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Python
      id: install-python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Load Poetry cache
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-py-${{ steps.install-python.outputs.python-version }}-poetry-cache-${{ hashFiles('docs/poetry.lock') }}

    - name: Install Poetry
      uses: Gr1N/setup-poetry@v8

    - name: Install Poetry dependencies
      run: |
        cd docs
        poetry install

    - name: load PlatformIO cache
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-py-${{ steps.install-python.outputs.python-version }}-pio-cache-${{ hashFiles('**/platformio.ini') }}

    - name: Install OS dependencies
      run: |
        sudo apt install python3-clang
        sudo apt install doxygen

    - name: Sphinx build
      run: |
        cd docs
        source .venv/bin/activate
        cd sphinx
        make clean
        make docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/sphinx/_build/html
        force_orphan: true
