name: PIO run static code analysis

on:
  workflow_dispatch:
  #push:
  #  paths:
  #    - "**/*.h"
  #    - "**/*.c"
  #    - "**/*.cpp"
  #    - "**/platformio.ini"
  #    - "!.github/workflows/**/*"
  #    - ".github/workflows/pio-check.yaml"
  #pull_request:
  #  paths:
  #    - "**/*.h"
  #    - "**/*.c"
  #    - "**/*.cpp"
  #    - "**/platformio.ini"
  #    - "!.github/workflows/**/*"
  #    - ".github/workflows/pio-check.yaml"

jobs:
  pio-check:
    name: PIO static code analysis on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prerequisites
        uses: ./.github/actions/checkout-python-poetry-platformio

      - name: Static code analysis
        run: |
          cd utils
          source .venv/bin/activate
          cd -
          platformio check --fail-on-defect=high --fail-on-defect=medium --fail-on-defect=low --verbose
