name: PIO run static code analysis

on:
  workflow_dispatch:
  #push:
  #  paths:
  #    - "**/*.c"
  #    - "**/*.cpp"
  #    - "**/*.h"
  #    - "**/*platformio.ini"
  #    - "!.github/workflows/**"
  #    - ".github/workflows/pio-check.yaml"
  #pull_request:
  #  paths:
  #    - "**/*.c"
  #    - "**/*.cpp"
  #    - "**/*.h"
  #    - "**/*platformio.ini"
  #    - "!.github/workflows/**"
  #    - ".github/workflows/pio-check.yaml"

jobs:
  pio-check:
    name: PIO static code analysis on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Python
        id: prepare-python
        uses: ./.github/actions/python

      - name: Prepare Poetry
        uses: ./.github/actions/poetry
        with:
          python-version: ${{ steps.prepare-python.outputs.python-version }}

      - name: Prepare Platformio
        uses: ./.github/actions/platformio
        with:
          python-version: ${{ steps.prepare-python.outputs.python-version }}

      - name: Static code analysis
        run: |
          cd utils
          source .venv/bin/activate
          cd -
          platformio check --fail-on-defect=high --fail-on-defect=medium --fail-on-defect=low --verbose
