name: PIO build all targets

on:
  workflow_dispatch:
  #push:
  #  paths:
  #    - "**/*.c"
  #    - "**/*.cpp"
  #    - "**/*.h"
  #    - "**/*platformio.ini"
  #    - "!.github/workflows/**"
  #    - ".github/workflows/pio-run.yaml"
  #pull_request:
  #  paths:
  #    - "**/*.c"
  #    - "**/*.cpp"
  #    - "**/*.h"
  #    - "**/*platformio.ini"
  #    - "!.github/workflows/**"
  #    - ".github/workflows/pio-run.yaml"

jobs:
  pio-run:
    name: Build all targets on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prerequisites
        uses: ./.github/actions/checkout-python-poetry-platformio

      - name: Build targets
        run: |
          cd utils
          source .venv/bin/activate
          cd -
          platformio run --verbose
