name: PIO build all targets

on:
  push:
    paths:
      - "**/*.c"
      - "**/*.cpp"
      - "**/*.h"
      - "**/*platformio.ini"
      - "!.github/workflows/**"
      - ".github/workflows/pio-run.yaml"
  pull_request:
    paths:
      - "**/*.c"
      - "**/*.cpp"
      - "**/*.h"
      - "**/*platformio.ini"
      - "!.github/workflows/**"
      - ".github/workflows/pio-run.yaml"

jobs:
  pio-run:
    name: Build all targets on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Python
      id: install-python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Load Poetry cache
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-py-${{ steps.install-python.outputs.python-version }}-poetry-cache-${{ hashFiles('utils/poetry.lock') }}

    - name: Install Poetry
      uses: Gr1N/setup-poetry@v8

    - name: Install Poetry dependencies
      run: |
        cd utils
        poetry install

    - name: load PlatformIO cache
      uses: actions/cache@v3
      with:
        path: | 
          ~/.cache/pip
          ~/.platformio
        key: ${{ runner.os }}-py-${{ steps.install-python.outputs.python-version }}-pio-cache-${{ hashFiles('**/platformio.ini') }}

    - name: Build targets
      run: |
        cd utils
        source .venv/bin/activate
        cd -
        platformio run --verbose
