name: PIO run native unit tests

on:
  workflow_dispatch:
  #push:
  #  paths:
  #    - "**/*.h"
  #    - "**/*.c"
  #    - "**/*.cpp"
  #    - "**/platformio.ini"
  #    - "!.github/workflows/**/*"
  #    - ".github/workflows/unit-tests.yaml"
  #pull_request:
  #  paths:
  #    - "**/*.h"
  #    - "**/*.c"
  #    - "**/*.cpp"
  #    - "**/platformio.ini"
  #    - "!.github/workflows/**/*"
  #    - ".github/workflows/unit-tests.yaml"

jobs:
  unit-tests:
    name: Native unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prerequisites
        uses: ./.github/actions/checkout-python-poetry-platformio

      - name: Unit tests
        run: |
          cd utils
          source .venv/bin/activate
          cd -
          platformio test --environment test_native --verbose
